# Accident Information Dataset

In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('Accident_Information.csv')
print(data.head())

C:\Users\saurabh singh\AppData\Local\Temp\ipykernel_17328\1269509483.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Accident_Information.csv')


  Accident_Index 1st_Road_Class  1st_Road_Number 2nd_Road_Class  \
0  200501BS00001              A           3218.0            NaN   
1  200501BS00002              B            450.0              C   
2  200501BS00003              C              0.0            NaN   
3  200501BS00004              A           3220.0            NaN   
4  200501BS00005   Unclassified              0.0            NaN   

   2nd_Road_Number Accident_Severity Carriageway_Hazards        Date  \
0              0.0           Serious                 NaN  2005-01-04   
1              0.0            Slight                 NaN  2005-01-05   
2              0.0            Slight                 NaN  2005-01-06   
3              0.0            Slight                 NaN  2005-01-07   
4              0.0            Slight                 NaN  2005-01-10   

  Day_of_Week  Did_Police_Officer_Attend_Scene_of_Accident  ...  \
0     Tuesday                                          1.0  ...   
1   Wednesday                 

## Removing first column

In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv('Accident_Information.csv')

#remove accident id coloumn
data.drop('Accident_Index', axis=1, inplace=True)
data.to_csv('col1_removed.csv', index=False)

C:\Users\saurabh singh\AppData\Local\Temp\ipykernel_17328\1676885017.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Accident_Information.csv')


In [3]:
import pandas as pd
data = pd.read_csv('col1_removed.csv')
# Assuming 'data' is your DataFrame
column_data_types = data.dtypes
print(column_data_types)

1st_Road_Class                                  object
1st_Road_Number                                float64
2nd_Road_Class                                  object
2nd_Road_Number                                float64
Accident_Severity                               object
Carriageway_Hazards                             object
Date                                            object
Day_of_Week                                     object
Did_Police_Officer_Attend_Scene_of_Accident    float64
Junction_Control                                object
Junction_Detail                                 object
Latitude                                       float64
Light_Conditions                                object
Local_Authority_(District)                      object
Local_Authority_(Highway)                       object
Location_Easting_OSGR                          float64
Location_Northing_OSGR                         float64
Longitude                                      float64
LSOA_of_Ac

## Data filtering

In [13]:
import pandas as pd
import numpy as np

data=pd.read_csv('col1_removed.csv')
data.replace("Unclassified",np.nan, inplace=True)
data.replace("Data missing or out of range",np.nan, inplace=True)
data.to_csv('Null_values.csv', index=False)

In [11]:
import pandas as pd
data = pd.read_csv('Null_values.csv')
# Assuming 'data' is your DataFrame
data.isna().sum()

1st_Road_Class                                  603938
1st_Road_Number                                      2
2nd_Road_Class                                 1659255
2nd_Road_Number                                  17593
Accident_Severity                                    0
Carriageway_Hazards                            2010553
Date                                                 0
Day_of_Week                                          0
Did_Police_Officer_Attend_Scene_of_Accident        278
Junction_Control                                754311
Junction_Detail                                    734
Latitude                                           174
Light_Conditions                                    14
Local_Authority_(District)                           0
Local_Authority_(Highway)                            0
Location_Easting_OSGR                              164
Location_Northing_OSGR                             164
Longitude                                          175
LSOA_of_Ac

## Dropping unneccessary column

In [16]:
import pandas as pd
import numpy as np

data = pd.read_csv('Null_values.csv')

remove accident id coloumn
data.drop('1st_Road_Class', axis=1, inplace=True)
data.drop('2nd_Road_Class', axis=1, inplace=True)
data.drop('Carriageway_Hazards', axis=1, inplace=True)
data.drop('Junction_Control', axis=1, inplace=True)
data.drop('LSOA_of_Accident_Location', axis=1, inplace=True)
data.drop('Special_Conditions_at_Site', axis=1, inplace=True)
data.drop('Location_Easting_OSGR', axis=1, inplace=True)
data.drop('Location_Northing_OSGR', axis=1, inplace=True)
data.to_csv('Cols_reduced1.csv', index=False)

In [15]:
print(data.head())

   1st_Road_Number  2nd_Road_Number Accident_Severity        Date Day_of_Week  \
0           3218.0              0.0           Serious  2005-01-04     Tuesday   
1            450.0              0.0            Slight  2005-01-05   Wednesday   
2              0.0              0.0            Slight  2005-01-06    Thursday   
3           3220.0              0.0            Slight  2005-01-07      Friday   
4              0.0              0.0            Slight  2005-01-10      Monday   

   Did_Police_Officer_Attend_Scene_of_Accident  \
0                                          1.0   
1                                          1.0   
2                                          1.0   
3                                          1.0   
4                                          1.0   

                       Junction_Detail   Latitude  \
0  Not at junction or within 20 metres  51.489096   
1                           Crossroads  51.520075   
2  Not at junction or within 20 metres  51.525301   


## Changing Datetime format and creating new column named "Time_of_day" 

In [17]:
#change time and date
import pandas as pd
data = pd.read_csv('Cols_reduced1.csv')
# Assuming 'data' is your DataFrame containing the encoded data
data['Time'] = pd.to_datetime(data['Time'], format='%H:%M')

# Create a new column 'Time_of_Day' based on the 'Time' column
data['Time_of_Day'] = data['Time'].dt.hour.apply(
    lambda x: 'Morning' if 5 <= x < 12 else ('Evening' if 12 <= x < 18 else 'Night')
)
data.drop('Time', axis=1, inplace=True)
data.drop('Date', axis=1, inplace=True)
data.to_csv('Time&Date_changed.csv', index=False)

In [18]:
print(data.head())

   1st_Road_Number  2nd_Road_Number Accident_Severity Day_of_Week  \
0           3218.0              0.0           Serious     Tuesday   
1            450.0              0.0            Slight   Wednesday   
2              0.0              0.0            Slight    Thursday   
3           3220.0              0.0            Slight      Friday   
4              0.0              0.0            Slight      Monday   

   Did_Police_Officer_Attend_Scene_of_Accident  \
0                                          1.0   
1                                          1.0   
2                                          1.0   
3                                          1.0   
4                                          1.0   

                       Junction_Detail   Latitude  \
0  Not at junction or within 20 metres  51.489096   
1                           Crossroads  51.520075   
2  Not at junction or within 20 metres  51.525301   
3  Not at junction or within 20 metres  51.482442   
4  Not at junction 

### Encodng dataset

In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load your cleaned dataset with missing values replaced (replace 'cleaned_dataset.csv' with your data file)
data = pd.read_csv('Time&Date_changed.csv')

# Initialize label encoders for categorical columns
categorical_columns = ['Accident_Severity','Day_of_Week','Junction_Detail','Light_Conditions','Local_Authority_(District)','Local_Authority_(Highway)','Police_Force','Road_Surface_Conditions','Road_Type','Urban_or_Rural_Area','Weather_Conditions','InScotland','Year','Time_of_Day']
label_encoders = {}

for col in categorical_columns:
    label_encoders[col] = LabelEncoder()
    data[col] = label_encoders[col].fit_transform(data[col])

# Save the encoded dataset to a new CSV file
data.to_csv('Encoded_dataset.csv', index=False)

In [23]:
import pandas as pd
data = pd.read_csv('Encoded_dataset.csv')
# Assuming 'data' is your DataFrame
data.isna().sum()

1st_Road_Number                                    2
2nd_Road_Number                                17593
Accident_Severity                                  0
Day_of_Week                                        0
Did_Police_Officer_Attend_Scene_of_Accident      278
Junction_Detail                                    0
Latitude                                         174
Light_Conditions                                   0
Local_Authority_(District)                         0
Local_Authority_(Highway)                          0
Longitude                                        175
Number_of_Casualties                               0
Number_of_Vehicles                                 0
Pedestrian_Crossing-Human_Control               2920
Pedestrian_Crossing-Physical_Facilities         3560
Police_Force                                       0
Road_Surface_Conditions                            0
Road_Type                                          0
Speed_limit                                   

### Filling null values using the mean of the particular column

In [25]:
import pandas as pd
import numpy as np

# Load your dataset
data = pd.read_csv('Encoded_dataset.csv')

# Calculate the floor division of the mean of each column
mean_floor_divided = data.mean().apply(np.floor)

# Replace null values with the floor-divided mean of each column
data = data.fillna(mean_floor_divided)

# Save the updated dataset to a new CSV file
data.to_csv('Filled_with_floor_divided_mean_dataset.csv', index=False)

In [26]:
import pandas as pd
data = pd.read_csv('Filled_with_floor_divided_mean_dataset.csv')
# Assuming 'data' is your DataFrame
data.isna().sum()

1st_Road_Number                                0
2nd_Road_Number                                0
Accident_Severity                              0
Day_of_Week                                    0
Did_Police_Officer_Attend_Scene_of_Accident    0
Junction_Detail                                0
Latitude                                       0
Light_Conditions                               0
Local_Authority_(District)                     0
Local_Authority_(Highway)                      0
Longitude                                      0
Number_of_Casualties                           0
Number_of_Vehicles                             0
Pedestrian_Crossing-Human_Control              0
Pedestrian_Crossing-Physical_Facilities        0
Police_Force                                   0
Road_Surface_Conditions                        0
Road_Type                                      0
Speed_limit                                    0
Urban_or_Rural_Area                            0
Weather_Conditions  

### Using Random Forrest classifier to train on model with mean filled data

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load the encoded dataset
data = pd.read_csv('Filled_with_floor_divided_mean_dataset.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Generate a confusion matrix
confusion = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion)

# Calculate accuracy and display classification report
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy * 100))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[     6    207   5049]
 [    25   1407  55998]
 [    55   2585 344120]]

Accuracy: 84.39%

Classification Report:
              precision    recall  f1-score   support

           0       0.07      0.00      0.00      5262
           1       0.34      0.02      0.05     57430
           2       0.85      0.99      0.92    346760

    accuracy                           0.84    409452
   macro avg       0.42      0.34      0.32    409452
weighted avg       0.77      0.84      0.78    409452



### Using Logistic Regression as training model with mean filled data

In [4]:
# Step 1: Import the necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the encoded dataset
data = pd.read_csv('Filled_with_floor_divided_mean_dataset.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]


# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Create a Logistic Regression classifier and train it on the training data
logistic_classifier = LogisticRegression(max_iter=1000)
logistic_classifier.fit(X_train, y_train)

# Step 5: Make predictions on the test data
y_pred = logistic_classifier.predict(X_test)

# Step 6: Evaluate the classifier's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Step 7: Print the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.8468636128288541
Classification Report:


C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00      5262
           1       0.39      0.00      0.00     57430
           2       0.85      1.00      0.92    346760

    accuracy                           0.85    409452
   macro avg       0.41      0.33      0.31    409452
weighted avg       0.77      0.85      0.78    409452

Confusion Matrix:
[[     0     20   5242]
 [     0     56  57374]
 [     0     66 346694]]


### Using Random forest with 3 phase data with mean filled data with split size 70-20-10

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load the encoded dataset
data = pd.read_csv('Filled_with_floor_divided_mean_dataset.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the data into training (70%), validation (20%), and testing (10%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=1/3, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the validation data
y_val_pred = clf.predict(X_val)

# Generate a confusion matrix for validation
confusion_val = confusion_matrix(y_val, y_val_pred)

# Print the confusion matrix for validation
print("Validation Confusion Matrix:")
print(confusion_val)

# Calculate accuracy and display classification report for validation
accuracy_val = accuracy_score(y_val, y_val_pred)
print("\nValidation Accuracy: {:.2f}%".format(accuracy_val * 100))
print("\nValidation Classification Report:")
print(classification_report(y_val, y_val_pred))

# Make predictions on the testing data
y_test_pred = clf.predict(X_test)

# Generate a confusion matrix for testing
confusion_test = confusion_matrix(y_test, y_test_pred)

# Print the confusion matrix for testing
print("\nTesting Confusion Matrix:")
print(confusion_test)

# Calculate accuracy and display classification report for testing
accuracy_test = accuracy_score(y_test, y_test_pred)
print("\nTesting Accuracy: {:.2f}%".format(accuracy_test * 100))
print("\nTesting Classification Report:")
print(classification_report(y_test, y_test_pred))


Validation Confusion Matrix:
[[    10    226   4975]
 [    26   1367  55826]
 [    62   2555 344404]]

Validation Accuracy: 84.45%

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.10      0.00      0.00      5211
           1       0.33      0.02      0.04     57219
           2       0.85      0.99      0.92    347021

    accuracy                           0.84    409451
   macro avg       0.43      0.34      0.32    409451
weighted avg       0.77      0.84      0.78    409451


Testing Confusion Matrix:
[[     4    105   2551]
 [    11    702  27910]
 [    19   1314 172110]]

Testing Accuracy: 84.41%

Testing Classification Report:
              precision    recall  f1-score   support

           0       0.12      0.00      0.00      2660
           1       0.33      0.02      0.05     28623
           2       0.85      0.99      0.92    173443

    accuracy                           0.84    204726
   macro avg       0.43

### Filling null values with mode of the particular column

In [6]:
import pandas as pd
import numpy as np

# Load your dataset
data = pd.read_csv('Encoded_dataset.csv')

# Replace NaN values in each column with the mode of that column
for column in data.columns:
    mode_value = data[column].mode().iloc[0]  # Calculate the mode

    # Replace NaN values with the mode value in the current column
    data[column].fillna(mode_value, inplace=True)

data.to_csv('Mode_filtered_data.csv', index=False)

In [7]:
data.isna().sum()

1st_Road_Number                                0
2nd_Road_Number                                0
Accident_Severity                              0
Day_of_Week                                    0
Did_Police_Officer_Attend_Scene_of_Accident    0
Junction_Detail                                0
Latitude                                       0
Light_Conditions                               0
Local_Authority_(District)                     0
Local_Authority_(Highway)                      0
Longitude                                      0
Number_of_Casualties                           0
Number_of_Vehicles                             0
Pedestrian_Crossing-Human_Control              0
Pedestrian_Crossing-Physical_Facilities        0
Police_Force                                   0
Road_Surface_Conditions                        0
Road_Type                                      0
Speed_limit                                    0
Urban_or_Rural_Area                            0
Weather_Conditions  

### Using Random forrest classifier with mode filled data with training and testing size 80-20

In [8]:
#Training model with another dataset
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load the encoded dataset
data = pd.read_csv('Mode_filtered_data.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Generate a confusion matrix
confusion = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion)

# Calculate accuracy and display classification report
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy * 100))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[     6    206   5050]
 [    22   1387  56021]
 [    56   2597 344107]]

Accuracy: 84.38%

Classification Report:
              precision    recall  f1-score   support

           0       0.07      0.00      0.00      5262
           1       0.33      0.02      0.05     57430
           2       0.85      0.99      0.92    346760

    accuracy                           0.84    409452
   macro avg       0.42      0.34      0.32    409452
weighted avg       0.77      0.84      0.78    409452



### Using Random forrest classifier with mode filled data with training and testing size 70-30

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load the encoded dataset
data = pd.read_csv('Mode_filtered_data.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Generate a confusion matrix
confusion = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion)

# Calculate accuracy and display classification report
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: {:.2f}%".format(accuracy * 100))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[    15    329   7527]
 [    43   2037  83762]
 [    81   3833 516550]]

Accuracy: 84.44%

Classification Report:
              precision    recall  f1-score   support

           0       0.11      0.00      0.00      7871
           1       0.33      0.02      0.04     85842
           2       0.85      0.99      0.92    520464

    accuracy                           0.84    614177
   macro avg       0.43      0.34      0.32    614177
weighted avg       0.77      0.84      0.78    614177



### Using Random Forrest model on mode filled data with data split size 70-20-10

In [10]:
#Using Random forest with 3 phase data
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load the encoded dataset
data = pd.read_csv('Mode_filtered_data.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the data into training (70%), validation (20%), and testing (10%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=1/3, random_state=42)

# Initialize the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the validation data
y_val_pred = clf.predict(X_val)

# Generate a confusion matrix for validation
confusion_val = confusion_matrix(y_val, y_val_pred)

# Print the confusion matrix for validation
print("Validation Confusion Matrix:")
print(confusion_val)

# Calculate accuracy and display classification report for validation
accuracy_val = accuracy_score(y_val, y_val_pred)
print("\nValidation Accuracy: {:.2f}%".format(accuracy_val * 100))
print("\nValidation Classification Report:")
print(classification_report(y_val, y_val_pred))

# Make predictions on the testing data
y_test_pred = clf.predict(X_test)

# Generate a confusion matrix for testing
confusion_test = confusion_matrix(y_test, y_test_pred)

# Print the confusion matrix for testing
print("\nTesting Confusion Matrix:")
print(confusion_test)

# Calculate accuracy and display classification report for testing
accuracy_test = accuracy_score(y_test, y_test_pred)
print("\nTesting Accuracy: {:.2f}%".format(accuracy_test * 100))
print("\nTesting Classification Report:")
print(classification_report(y_test, y_test_pred))


Validation Confusion Matrix:
[[    12    229   4970]
 [    29   1352  55838]
 [    58   2565 344398]]

Validation Accuracy: 84.45%

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.12      0.00      0.00      5211
           1       0.33      0.02      0.04     57219
           2       0.85      0.99      0.92    347021

    accuracy                           0.84    409451
   macro avg       0.43      0.34      0.32    409451
weighted avg       0.77      0.84      0.78    409451


Testing Confusion Matrix:
[[     3    100   2557]
 [    14    685  27924]
 [    23   1268 172152]]

Testing Accuracy: 84.43%

Testing Classification Report:
              precision    recall  f1-score   support

           0       0.07      0.00      0.00      2660
           1       0.33      0.02      0.04     28623
           2       0.85      0.99      0.92    173443

    accuracy                           0.84    204726
   macro avg       0.42

### Using Logistic Regression as training model with mode filled data

In [2]:
#Using logistic regression
# Step 1: Import the necessary libraries
import pandas as pd
import numpy 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the encoded dataset
data = pd.read_csv('Mode_filtered_data.csv')

# Assuming 'target_column' is the name of the column you want to predict
# Replace 'target_column' with the actual name of the target column
target_column = 'Accident_Severity'

# Split the data into features (X) and the target (y)
X = data.drop(columns=[target_column])
y = data[target_column]


# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Create a Logistic Regression classifier and train it on the training data
logistic_classifier = LogisticRegression(max_iter=1000)
logistic_classifier.fit(X_train, y_train)

# Step 5: Make predictions on the test data
y_pred = logistic_classifier.predict(X_test)

# Step 6: Evaluate the classifier's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Step 7: Print the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.8474153216418069
Classification Report:


C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00      7871
           1       0.43      0.00      0.00     85842
           2       0.85      1.00      0.92    520464

    accuracy                           0.85    614177
   macro avg       0.42      0.33      0.31    614177
weighted avg       0.78      0.85      0.78    614177

Confusion Matrix:
[[     0     18   7853]
 [     0     56  85786]
 [     0     57 520407]]


C:\Users\saurabh singh\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
